In [1]:
import numpy as np
import pandas as pd
import math

In [7]:
graph = {
    'a': {'b': 85, 'c': 217, 'e': 173},
    'b': {'f': 80},
    'c': {'g': 186, 'h': 103},
    'd': dict(),
    'e': {'j': 502},
    'f': {'i': 250},
    'g': dict(),
    'h': {'d': 183, 'j': 167},
    'i': {'j': 84},
    'j': dict()
        }

In [19]:
def dijkstra(graph = graph, source = 'a'):
    
    dist_matrix = pd.DataFrame(columns = sorted(graph.keys()))
    dist_matrix.loc[0] = [0] + [math.inf] * (len(dist_matrix.columns) - 1)
    
    vertex = source
    
    path = {'a': 'a'}
    
    while len(dist_matrix) <= len(dist_matrix.columns) + 1:
        
        mat_length = len(dist_matrix) - 1
        print('matrix length:', mat_length)
        
        dist_matrix.loc[vertex] = dist_matrix.iloc[mat_length]
        
        for key in graph[vertex]:
            dist_matrix.loc[vertex][key] = int(min(dist_matrix.loc[vertex][key],
                                               dist_matrix.iloc[mat_length][vertex] + graph[vertex][key]))
            
        try: # Get the next minimum distance
            vertex = dist_matrix.drop(dist_matrix.index[1:], axis = 1).loc[vertex].idxmin()
            print(vertex)
            
        except:
            return(dist_matrix)

In [165]:
def dijkstra(graph = graph, source = 'a', path = True):
    
    dist_matrix = pd.DataFrame(columns = sorted(graph.keys()))
    dist_matrix.loc[0] = [0] + [math.inf] * (len(dist_matrix.columns) - 1)
    
    vertex = source
    
    path = {'a': 'a'}
    
    while len(dist_matrix) <= len(dist_matrix.columns) + 1:
        
        mat_length = len(dist_matrix) - 1
        print('matrix length:', mat_length)
        
        dist_matrix.loc[vertex] = dist_matrix.iloc[mat_length]
        
        for key in graph[vertex]:
            
            if dist_matrix.loc[vertex][key] > dist_matrix.iloc[mat_length][vertex] + graph[vertex][key]:
                dist_matrix.loc[vertex][key] = dist_matrix.iloc[mat_length][vertex] + graph[vertex][key]
                path[key] = path[vertex] + key
            
        try: # Get the next minimum distance
            vertex = dist_matrix.drop(dist_matrix.index[1:], axis = 1).loc[vertex].idxmin()
            print(vertex)
            
        except:
            if path == True:
                return(path)
            else:
                return(dist_matrix)

In [14]:
sorted(list(graph.keys()))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [166]:
dijkstra(path = False)

matrix length: 0
b
matrix length: 1
f
matrix length: 2
e
matrix length: 3
c
matrix length: 4
h
matrix length: 5
g
matrix length: 6
i
matrix length: 7
j
matrix length: 8
d
matrix length: 9

,a,b,c,d,e,f,g,h,i,j
0,0.0,inf,inf,inf,inf,inf,inf,inf,inf,inf
a,0.0,85.000000,217.000000,inf,173.000000,inf,inf,inf,inf,inf
b,0.0,85.000000,217.000000,inf,173.000000,165.000000,inf,inf,inf,inf
f,0.0,85.000000,217.000000,inf,173.000000,165.000000,inf,inf,415.000000,inf
e,0.0,85.000000,217.000000,inf,173.000000,165.000000,inf,inf,415.000000,675.000000
c,0.0,85.000000,217.000000,inf,173.000000,165.000000,403.000000,320.000000,415.000000,675.000000
h,0.0,85.000000,217.000000,503.000000,173.000000,165.000000,403.000000,320.000000,415.000000,487.000000
g,0.0,85.000000,217.000000,503.000000,173.000000,165.000000,403.000000,320.000000,415.000000,487.000000
i,0.0,85.000000,217.000000,503.000000,173.000000,165.000000,403.000000,320.000000,415.000000,487.000000
j,0.0,85.000000,217.000000,503.000000,173.000000,165.000000,403.000000,320.000000,415.000000,487.000000
d,0.0,85.000000,217.000000,503.000000,173.000000,165.000000,403.000000,320.000000,415.000000,487.000000

In [176]:
# First attempt at a mapper
def mapper(graph = graph):
    
    print('# Path:\ta')
    
    for key in graph.keys():
        if key not in graph['a']:
            graph['a'][key] = math.inf
    
    for vertex in sorted(list(graph.keys())):
        for key in sorted(list(graph[vertex].keys())):
            print(vertex + key, graph[vertex][key])

mapper()

# Path:	a
aa 0
ab 85
ac 217
ad inf
ae 173
af inf
ag inf
ah inf
ai inf
aj inf
bf 80
cg 186
ch 103
ej 502
fi 250
hd 183
hj 167
ij 84

In [171]:
text = """# Path:	ab
ah inf
ac 217
ad inf
ae 173
aj inf
ab 85
aa 0
af inf
ai inf
ag inf
bf 80
hd 183
hj 167
fi 250
ij 84
cg 186
ch 103
ej 502"""

In [172]:
def reducer(text):
    
    a_graph = dict()
    r_graph = dict()
    
    text = text.split('\n')
    path = text[0].split('\t')[1]
    vertex = path[-1]
    
    for line in text[1:]: # First loop to define the two dictionaries
        line = line.split(' ')
        
        if line[0][0] == 'a': # First dictionary (that is going to be our final result)
            if line[1] == 'inf':
                a_graph[line[0][1]] = math.inf
            else:
                a_graph[line[0][1]] = int(line[1])
        
        else:
            r_graph[line[0]] = int(line[1]) # Second dictionary, with all 'secondary' nodes
            
            if line[0][0] == vertex:
                a_graph[line[0][1]] = min(a_graph[line[0][1]], a_graph[line[0][0]] + int(line[1]))
            
    path_graph = {key: a_graph[key] for key in a_graph if key not in path} # To get the next vertex for the algorithm
    
    try:
        print('# Path:\t%s' % path + min(path_graph, key = path_graph.get))
        
    except ValueError:
        print('# Finished')
    
    for key in a_graph:
        print('a' + key + '', a_graph[key])
        
    for key in r_graph:
        print(key + '', r_graph[key])

reducer(text = text)

# Path:	abf
ah inf
ac 217
ad inf
ae 173
ab 85
aa 0
ag inf
af 165
ai inf
aj inf
ch 103
bf 80
hd 183
fi 250
ej 502
cg 186
hj 167
ij 84

In [84]:
{key: graph[key] for key in graph if key not in ['a', 'c', 'e']}

{'b': {'f': 80},
 'd': {},
 'f': {'i': 250},
 'g': {},
 'h': {'d': 183, 'j': 167},
 'i': {'j': 84},
 'j': {}}

In [1]:
import scipy.sparse
import os
import pandas as pd
import numpy as np

In [4]:
def dijkstra_check(text):
    
    sparse_matrix = np.array(text).transpose()
    
    dimension = max(max(sparse_matrix[0]), max(sparse_matrix[1]))

    matrix = np.zeros((dimension, dimension))

    for ind1, ind2, weight in zip(sparse_matrix[0], sparse_matrix[1], sparse_matrix[2]):
        ind1 -= 1
        ind2 -= 1
        matrix[ind1][ind2] = weight
        matrix[ind2][ind1] = weight
     
    return(pd.DataFrame(scipy.sparse.csgraph.dijkstra(matrix),
                        columns = range(1, dimension + 1),
                        index = range(1, dimension + 1)))

text = pd.read_csv('sparse_matrix_3.txt', sep = ";", names = ['a','b','c'], dtype = int)

dijkstra_check(text)

      1     2     3     4     5     6     7     8     9
1   0.0   4.0  12.0  19.0  21.0  11.0   9.0   8.0  14.0
2   4.0   0.0   8.0  15.0  22.0  12.0  12.0  11.0  10.0
3  12.0   8.0   0.0   7.0  14.0   4.0   6.0   7.0   2.0
4  19.0  15.0   7.0   0.0   9.0  11.0  13.0  14.0   9.0
5  21.0  22.0  14.0   9.0   0.0  10.0  12.0  13.0  16.0
6  11.0  12.0   4.0  11.0  10.0   0.0   2.0   3.0   6.0
7   9.0  12.0   6.0  13.0  12.0   2.0   0.0   1.0   6.0
8   8.0  11.0   7.0  14.0  13.0   3.0   1.0   0.0   7.0
9  14.0  10.0   2.0   9.0  16.0   6.0   6.0   7.0   0.0

In [54]:
pd.DataFrame(scipy.sparse.csgraph.dijkstra(matrix))

       0      1      2      3      4      5      6      7      8      9
0    0.0   85.0  217.0  503.0  173.0  165.0  403.0  320.0  415.0  487.0
1   85.0    0.0  302.0  588.0  258.0   80.0  488.0  405.0  330.0  414.0
2  217.0  302.0    0.0  286.0  390.0  382.0  186.0  103.0  354.0  270.0
3  503.0  588.0  286.0    0.0  676.0  668.0  472.0  183.0  434.0  350.0
4  173.0  258.0  390.0  676.0    0.0  338.0  576.0  493.0  586.0  502.0
5  165.0   80.0  382.0  668.0  338.0    0.0  568.0  485.0  250.0  334.0
6  403.0  488.0  186.0  472.0  576.0  568.0    0.0  289.0  540.0  456.0
7  320.0  405.0  103.0  183.0  493.0  485.0  289.0    0.0  251.0  167.0
8  415.0  330.0  354.0  434.0  586.0  250.0  540.0  251.0    0.0   84.0
9  487.0  414.0  270.0  350.0  502.0  334.0  456.0  167.0   84.0    0.0